version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin      # juste pour le moment
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: capgem     
    ports:
      - "5432:5432"                 
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data.csv:/docker-entrypoint-initdb.d/data.csv
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
