version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data.csv:/docker-entrypoint-initdb.d/data.csv
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql   
      - ./02-init.sh:/docker-entrypoint-initdb.d/02-init.sh   
                                  
                                      
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
